server:
  port: 8080
spring:
  application:
    name: spring-smooth-openfeign
  cloud:
    loadbalancer:
      enabled: true
      retry:
        # 该参数用来开启或关闭重试机制，默认是开启
        enabled: true
        # 对当前实例重试的次数，默认值: 0
        max-retries-on-same-service-instance: 1
        # 切换实例进行重试的次数，默认值: 1
        max-retries-on-next-service-instance: 1
        # 对所有的操作请求都进行重试
        retry-on-all-operations: true
      health-check:
        refetch-instances: true
        refetch-instances-interval: 5s
        repeat-health-check: false
#    circuitbreaker:
#      hystrix:
#        enabled: true
feign:
  okhttp:
    enabled: true        # ✅ 启用 OkHttp（可选）
  httpclient:
    enabled: false       # ✅ 禁用默认 HttpClient
  client:
    config:
      default:
        connectTimeout: 2000   # 毫秒
        readTimeout: 5000      # 毫秒
        loggerLevel: BASIC      # 打印详细日志（方便调试）



eureka:
  instance:
    metadata-map:
      version: @project.version@
    prefer-ip-address: true
  client:
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.70:9701/eureka


logging:
  level:
    com.netflix.loadbalancer: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    feign.Logger: DEBUG
    org.springframework.web: DEBUG